name: Release Multi-Arch macOS

permissions:
  contents: write  # Nécessaire pour créer la release et uploader les assets

on:
  push:
    tags:
      - 'v*.*.*'  # Se déclenche sur tags comme v1.4.5

jobs:
  build-arm64:
    name: Build ARM64 macOS
    runs-on: macos-latest  # Runner Apple Silicon actuel
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Convert PNG to ICNS
        run: sips -s format icns podcast.png --out podcast.icns

      - name: Build ARM64 executable with PyInstaller
        run: pyinstaller --name="Podcast Generator" --windowed --icon=podcast.icns gui.py

      - name: Package ARM64 zip
        run: zip -r Podcast_Generator_${{ github.ref_name }}_arm64.zip dist/Podcast\ Generator.app

      - name: Upload ARM64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: Podcast_Generator_arm64
          path: Podcast_Generator_${{ github.ref_name }}_arm64.zip

  build-intel:
    name: Build Intel macOS
    runs-on: [self-hosted, macos, x64]
    needs: build-arm64
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Convert PNG to ICNS
        run: sips -s format icns podcast.png --out podcast.icns

      - name: Build Intel executable with PyInstaller
        run: pyinstaller --name="Podcast Generator" --windowed --icon=podcast.icns gui.py

      - name: Package Intel zip
        run: zip -r Podcast_Generator_${{ github.ref_name }}_x86_64.zip dist/Podcast\ Generator.app

      - name: Upload Intel zip to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Installer GitHub CLI (nécessaire sur le runner self-hosted)
          if ! command -v gh &> /dev/null; then
            brew install gh
          fi
          gh release upload ${{ github.ref_name }} Podcast_Generator_${{ github.ref_name }}_x86_64.zip --clobber

  release:
    name: Create GitHub Release & Upload ARM64
    runs-on: ubuntu-latest
    needs: build-arm64
    steps:
      - uses: actions/checkout@v3

      - name: Download ARM64 artifact
        uses: actions/download-artifact@v4
        with:
          name: Podcast_Generator_arm64
          path: .

      - name: Create GitHub Release & Upload ARM64 zip
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: Podcast_Generator_${{ github.ref_name }}_arm64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
